name = "pillarworks/kit"
version = "0.1.0"
description = "the official pillarworks pillar creation kit"
authors = ["Primiti_ve"]
repository = "https://github.com/pillarworks-rbx/kit"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[dependencies]
framework = { name = "pillarworks/framework", version = "^0.1.1" }
group = { name = "pillarworks/group", version = "^0.1.2" }
region = { name = "pillarworks/region", version = "^0.1.1" }
iris = { wally = "sirmallard/iris", version = "^2.5.0" }
fluid = { wally = "ffrostfall/fluid", version = "^0.6.4" }
ui_labs = { wally = "pepeeltoro41/ui-labs", version = "^2.4.2" }
