# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.7.0-rc.1"
lune = "lune-org/lune@0.10.4"
blink = "1axen/blink@0.18.6"
darklua = "seaofvoices/darklua@0.17.3"
luau-lsp = "JohnnyMorganz/luau-lsp@1.59.0"
StyLua = "JohnnyMorganz/StyLua@2.3.1"
selene = "Kampfkarren/selene@0.29.0"